Gem::Specification.new do |s|
  s.name        = 'ig-identity-rp-validator'
  s.version     = '0.0.3'
  s.date        = '2015-07-16'
  s.summary     = 'Auth validator'
  s.description = 'Relying party validator for payloads generated by the id-io API'
  s.authors     = ['Infinity-G']
  s.email       = 'developer@infinity-g.com'
  s.files       = ['lib/ig-identity-rp-validator.rb']
  s.add_runtime_dependency 'ig-crypto-utils', ['>= 0.0.2']
  # s.add_development_dependency 'ig-crypto-utils', ['>= 0.0.2']
  s.homepage    = ''
  s.license     = 'MIT'
end

# run 'gem build ig-identity-rp-validator.gemspec' to create gem
# run 'gem push ig-identity-rp-validator-0.0.*.gem' to deploy